#CXX = /opt/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
CXXFLAGS = -std=c++11
LDLIBS = -lboost_system -pthread -lstdc++ -lssl -lcrypto -lmosquitto

gateway:
