#!/bin/bash

let id=$1+70

if [[ "$1" != "" && "$2" != "" ]]; then
    mosquitto_pub -h gate.patronage2020-iot.intive-projects.com -p 8883 -m '{"type":"windowBlind","id":'$id',"position":'$2'}' -t embedded_input --cafile /etc/ssl/certs/ca-certificates.crt  
else
    echo "Error"
fi